[package]
name = "zundamon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.22"
serde_json = "1.0.108"
tokio = "1.34.0"
winapi = { version = "0.3", features = ["winuser"] }
